version: '3'

services:
  pingua-cms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pingua-cms
    expose:
      - '7891'
    ports:
      - '7891:7891'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  node_modules:
